# Site settings
title:              OuestLab Portfolio 
email:              email@sample.com
description:        "Portfolio template for OuestLab"
url:                "https://ouestlab.github.io"
baseurl:            ""

footer-links:
  github: OuestLab
# File structure settings
image_path:         /public/images

github_username:  OuestLab
# Build settings
highlighter:        rouge
markdown:           kramdown
permalink:          pretty

